name: Auto Test

on: [push]

jobs:
  asm_run:
    name: Autorun Assembly
    runs-on: ubuntu-latest
    env:
      RUN_DIR: ~/assembly
      DOSBOX_TIMEOUT: 30
    steps:
      - uses: actions/checkout@v2
      - name: install dosbox
        run: |
          sudo apt-get update
          sudo apt-get install -y dosbox xvfb
      - name: get masm and config dosbox
        env:
          MASM_DOWNLOAD_URL: https://filedropper.com/d/s/download/BeMdA35QeYTUiwPU3QSMBXtuPLwYv4
          MASM_UNZIP_DIR: ~/masm
        run: |
          curl "${{ env.MASM_DOWNLOAD_URL }}" > ~/masm-bin.zip
          unzip ~/masm-bin.zip -d ${{ env.MASM_UNZIP_DIR }}
          DOSBOX_CONF=`dosbox -printconf`
          echo 'mount c '${{ env.MASM_UNZIP_DIR }} >> $DOSBOX_CONF
          echo 'mount d '${{ env.RUN_DIR }} >> $DOSBOX_CONF
          echo 'set PATH=%PATH%;C:\BIN\;' >> $DOSBOX_CONF
          echo 'd:' >> $DOSBOX_CONF
      - name: run problem 1 (MMOV)
        env:
          SOURCE_NAME: "1_MMOV.ASM"
        run: |
          rm -rf ${{ env.RUN_DIR }} && mkdir -p ${{ env.RUN_DIR }}
          cp ${{ env.SOURCE_NAME }} ${{ env.RUN_DIR }}/PROG.ASM
          echo -e 'PROG.OBJ\n\n\n' > ${{ env.RUN_DIR }}/MASM.IN
          echo -e 'PROG.EXE\n\n\n' > ${{ env.RUN_DIR }}/LINK.IN
          timeout ${{ env.DOSBOX_TIMEOUT }} xvfb-run --auto-servernum -e /dev/null dosbox \
            -c 'MASM PROG.ASM < MASM.IN' \
            -c 'LINK PROG.OBJ < LINK.IN' \
            -c 'PROG.EXE > PROG.OUT' \
            -c 'exit'
          echo 'Output result:'
          cat ${{ env.RUN_DIR }}/PROG.OUT
      - name: test problem 2 (SCMP)
        env:
          SOURCE_NAME: "2_SCMP.ASM"
          TESTCASES: "test/test2.txt"
          CHECKER: "scripts/strcmp_check.sh"
        run: |
          rm -rf ${{ env.RUN_DIR }} && mkdir -p ${{ env.RUN_DIR }}
          cp ${{ env.SOURCE_NAME }} ${{ env.RUN_DIR }}/PROG.ASM
          echo -e 'PROG.OBJ\n\n\n' > ${{ env.RUN_DIR }}/MASM.IN
          echo -e 'PROG.EXE\n\n\n' > ${{ env.RUN_DIR }}/LINK.IN
          timeout ${{ env.DOSBOX_TIMEOUT }} xvfb-run --auto-servernum -e /dev/null dosbox \
            -c 'MASM PROG.ASM < MASM.IN' \
            -c 'LINK PROG.OBJ < LINK.IN' \
            -c 'exit'
          for i in `cat ${{ env.TESTCASES }}`; do
            echo 'Running on test '$i
            echo -e $i'\r' > ${{ env.RUN_DIR }}/PROG.IN
            rm -f PROG.OUT
            timeout ${{ env.DOSBOX_TIMEOUT }} xvfb-run --auto-servernum -e /dev/null dosbox \
              -c 'PROG.EXE < PROG.IN > PROG.OUT' \
              -c 'exit' >/dev/null
            echo '- Input:'
            cat ${{ env.RUN_DIR }}/PROG.IN
            echo '- Output:'
            cat ${{ env.RUN_DIR }}/PROG.OUT
            echo
            bash ${{ env.CHECKER }} ${{ env.RUN_DIR }}/PROG.IN ${{ env.RUN_DIR }}/PROG.OUT
          done
      - name: test problem 3 (FIND)
        env:
          SOURCE_NAME: "3_FIND.ASM"
          TESTCASES: "test/test3.txt"
          CHECKER: "scripts/find_check.sh"
        run: |
          rm -rf ${{ env.RUN_DIR }} && mkdir -p ${{ env.RUN_DIR }}
          cp ${{ env.SOURCE_NAME }} ${{ env.RUN_DIR }}/PROG.ASM
          echo -e 'PROG.OBJ\n\n\n' > ${{ env.RUN_DIR }}/MASM.IN
          echo -e 'PROG.EXE\n\n\n' > ${{ env.RUN_DIR }}/LINK.IN
          timeout ${{ env.DOSBOX_TIMEOUT }} xvfb-run --auto-servernum -e /dev/null dosbox \
            -c 'MASM PROG.ASM < MASM.IN' \
            -c 'LINK PROG.OBJ < LINK.IN' \
            -c 'exit'
          for i in `cat ${{ env.TESTCASES }}`; do
            echo 'Running on test '$i
            echo -e $i'\r' > ${{ env.RUN_DIR }}/PROG.IN
            rm -f PROG.OUT
            timeout ${{ env.DOSBOX_TIMEOUT }} xvfb-run --auto-servernum -e /dev/null dosbox \
              -c 'PROG.EXE < PROG.IN > PROG.OUT' \
              -c 'exit' >/dev/null
            echo '- Input:'
            cat ${{ env.RUN_DIR }}/PROG.IN
            echo '- Output:'
            cat ${{ env.RUN_DIR }}/PROG.OUT
            echo
            bash ${{ env.CHECKER }} ${{ env.RUN_DIR }}/PROG.IN ${{ env.RUN_DIR }}/PROG.OUT
          done
      - name: test problem 4 (SORT)
        env:
          SOURCE_NAME: "4_SORT.ASM"
          TESTCASES: "test/test4.txt"
        run: |
          rm -rf ${{ env.RUN_DIR }} && mkdir -p ${{ env.RUN_DIR }}
          cp ${{ env.SOURCE_NAME }} ${{ env.RUN_DIR }}/PROG.ASM
          echo -e 'PROG.OBJ\n\n\n' > ${{ env.RUN_DIR }}/MASM.IN
          echo -e 'PROG.EXE\n\n\n' > ${{ env.RUN_DIR }}/LINK.IN
          timeout ${{ env.DOSBOX_TIMEOUT }} xvfb-run --auto-servernum -e /dev/null dosbox \
            -c 'MASM PROG.ASM < MASM.IN' \
            -c 'LINK PROG.OBJ < LINK.IN' \
            -c 'exit'
          for i in `cat ${{ env.TESTCASES }}`; do
            echo 'Running on test '$i
            echo -e $i'\r' > ${{ env.RUN_DIR }}/PROG.IN
            rm -f PROG.OUT
            timeout ${{ env.DOSBOX_TIMEOUT }} xvfb-run --auto-servernum -e /dev/null dosbox \
              -c 'PROG.EXE < PROG.IN > PROG.OUT' \
              -c 'exit' >/dev/null
            echo '- Input:'
            cat ${{ env.RUN_DIR }}/PROG.IN
            echo '- Output:'
            cat ${{ env.RUN_DIR }}/PROG.OUT
            echo
          done

          


